// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Microsoft.Rest;
using Newtonsoft.Json;

namespace ClientApplication.ExternalServices.ServerApplicationClient.Models
{
    public partial class SearchCriteria
    {
        /// <summary>
        /// Initializes a new instance of the SearchCriteria class.
        /// </summary>
        public SearchCriteria() { }

        /// <summary>
        /// Initializes a new instance of the SearchCriteria class.
        /// </summary>
        public SearchCriteria(string input, decimal rate, int propertyShouldNotBeNullable, int? id = default(int?))
        {
            Input = input;
            Id = id;
            Rate = rate;
            PropertyShouldNotBeNullable = propertyShouldNotBeNullable;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Input")]
        public string Input { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Rate")]
        public decimal Rate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PropertyShouldNotBeNullable")]
        public int PropertyShouldNotBeNullable { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Input == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Input");
            }
        }
    }
}
