// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using ClientApplication.ExternalServices.ServerApplicationClient.Models;
using Microsoft.Rest;

namespace ClientApplication.ExternalServices.ServerApplicationClient
{
    /// <summary>
    /// Search operations.
    /// </summary>
    public partial interface ISearch
    {
        /// <param name='criteria'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<SearchResult>>> PerformBestExSearchWithHttpMessagesAsync(SearchCriteria criteria, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
